apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-with-secret
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: ROOT_PASSWORD
#    - name: <another environment import if needed>
    ports:
    - containerPort: 3306
